import { X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: 'privacy' | 'terms' | null;
}

export default function LegalModal({ isOpen, onClose, type }: LegalModalProps) {
  if (!isOpen || !type) return null;

  const content = {
    privacy: {
      title: 'Privacy Policy',
      text: (
        <div className="space-y-4 text-slate-600 dark:text-slate-300 text-sm leading-relaxed">
          <p>Last updated: {new Date().toLocaleDateString()}</p>
          <h3 className="text-lg font-bold text-slate-900 dark:text-white mt-6">1. Introduction</h3>
          <p>Welcome to CreatorFlow. We respect your privacy and are committed to protecting your personal data. This privacy policy will inform you as to how we look after your personal data when you visit our website.</p>
          
          <h3 className="text-lg font-bold text-slate-900 dark:text-white mt-6">2. Data We Collect</h3>
          <p>We may collect, use, store and transfer different kinds of personal data about you which we have grouped together as follows:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Identity Data:</strong> includes first name, last name, username or similar identifier.</li>
            <li><strong>Contact Data:</strong> includes email address.</li>
            <li><strong>Usage Data:</strong> includes information about how you use our website, processing history, and video links.</li>
            <li><strong>Financial Data:</strong> processed securely via Stripe. We do not store your credit card details.</li>
          </ul>

          <h3 className="text-lg font-bold text-slate-900 dark:text-white mt-6">3. How We Use Your Data</h3>
          <p>We will only use your personal data when the law allows us to. Most commonly, we will use your personal data in the following circumstances:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Where we need to perform the contract we are about to enter into or have entered into with you.</li>
            <li>Where it is necessary for our legitimate interests (or those of a third party) and your interests and fundamental rights do not override those interests.</li>
          </ul>
        </div>
      )
    },
    terms: {
      title: 'Terms of Service',
      text: (
        <div className="space-y-4 text-slate-600 dark:text-slate-300 text-sm leading-relaxed">
          <p>Last updated: {new Date().toLocaleDateString()}</p>
          <h3 className="text-lg font-bold text-slate-900 dark:text-white mt-6">1. Acceptance of Terms</h3>
          <p>By accessing and using CreatorFlow, you accept and agree to be bound by the terms and provision of this agreement.</p>

          <h3 className="text-lg font-bold text-slate-900 dark:text-white mt-6">2. Subscription Services</h3>
          <p>CreatorFlow offers subscription-based services. By subscribing to a paid tier (Starter or Pro), you agree to pay the monthly subscription fees. You may cancel your subscription at any time. Refunds are processed solely at our discretion according to our refund policy.</p>

          <h3 className="text-lg font-bold text-slate-900 dark:text-white mt-6">3. API Usage and Fair Use</h3>
          <p>While the Pro plan offers unlimited generations, it is subject to a fair use policy. Automated scraping, reverse engineering our API, or utilizing our generation endpoints for external commercial services without an explicit license is strictly prohibited. Accounts violating fair use may be suspended.</p>

          <h3 className="text-lg font-bold text-slate-900 dark:text-white mt-6">4. Intellectual Property</h3>
          <p>The content generated by CreatorFlow is derived from the videos you submit. You retain all rights to the generated text, provided you have the legal right to the source video transcript. CreatorFlow is not responsible for copyright infringement originating from user-submitted videos.</p>
        </div>
      )
    }
  };

  const { title, text } = content[type];

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm"
        />
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 20 }}
          className="relative w-full max-w-2xl bg-white dark:bg-slate-900 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh]"
        >
          <div className="flex items-center justify-between p-6 border-b border-slate-100 dark:border-slate-800">
            <h2 className="text-2xl font-bold text-slate-900 dark:text-white">{title}</h2>
            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition-colors"
            >
              <X size={20} />
            </button>
          </div>
          
          <div className="p-6 overflow-y-auto">
            {text}
          </div>

          <div className="p-6 border-t border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-950/50 flex justify-end">
            <button
              onClick={onClose}
              className="px-6 py-2 bg-brand-600 hover:bg-brand-700 text-white font-medium rounded-xl transition-all shadow-sm"
            >
              I Understand
            </button>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
